import GRDB

/// 当前业务的完整初始结构，由账号级唯一迁移账本调用。
enum ChatSchema {
    /// 在账号基线迁移事务中依赖顺序建表，最后创建 ASCII tokenizer 的消息 FTS5 索引；建表失败向上抛出。
    static func create(in db: Database) throws {
        try UserProfileRecord.create(in: db)
        try ContactRecord.create(in: db)
        try ContactRequestRecord.create(in: db)
        try ContactActionRecord.create(in: db)
        try ConversationRecord.create(in: db)
        try MemberRecord.create(in: db)
        try MemberIntervalRecord.create(in: db)
        try ReadStateRecord.create(in: db)
        try LocalStateRecord.create(in: db)
        try PreferenceRecord.create(in: db)
        try AccountPreferenceRecord.create(in: db)
        try CheckpointRecord.create(in: db)
        try HiddenRecord.create(in: db)
        try HistoryRangeRecord.create(in: db)
        try AssetRecord.create(in: db)
        try AssetGeometryRecord.create(in: db)
        try AssetWaveRecord.create(in: db)
        try ResourceRecord.create(in: db)
        try AssetResourceRecord.create(in: db)
        try MessageRecord.create(in: db)
        try MessageTextRecord.create(in: db)
        try MessageLinkRecord.create(in: db)
        try MessageUnknownRecord.create(in: db)
        try MessageSystemRecord.create(in: db)
        try MessageRunRecord.create(in: db)
        try MessageReceiptRecord.create(in: db)
        try MessageAttachmentRecord.create(in: db)
        try SummaryRecord.create(in: db)
        try SummaryTextRecord.create(in: db)
        try SummaryLinkRecord.create(in: db)
        try SummaryUnknownRecord.create(in: db)
        try SummarySystemRecord.create(in: db)
        try SummaryRunRecord.create(in: db)
        try SummaryReceiptRecord.create(in: db)
        try SummaryAttachmentRecord.create(in: db)
        try SendTaskRecord.create(in: db)
        try SendRunRecord.create(in: db)
        try SendAssetRecord.create(in: db)
        try SendResourceRecord.create(in: db)
        try SendOrderRecord.create(in: db)
        try UploadBatchRecord.create(in: db)
        try UploadItemRecord.create(in: db)
        try UploadResourceRecord.create(in: db)
        try DraftRecord.create(in: db)
        try DraftAssetRecord.create(in: db)
        try DraftUploadItemRecord.create(in: db)
        try DraftUploadResourceRecord.create(in: db)
        try ResolutionRecord.create(in: db)
        try ContactOperationRecord.create(in: db)
        try ReeditRecord.create(in: db)
        try ReeditRunRecord.create(in: db)
        try TranscriptRecord.create(in: db)
        try PresentationRecord.create(in: db)
        try RetiredResourceRecord.create(in: db)
        try CleanupRecord.create(in: db)
        try DraftSegmentRecord.create(in: db)
        try DraftSegmentRunRecord.create(in: db)
        try DraftAttachmentRecord.create(in: db)
        try DraftMediaItemRecord.create(in: db)
        try DraftWaveRecord.create(in: db)
        try PresentationSegmentRecord.create(in: db)
        try PresentationSegmentRunRecord.create(in: db)
        try PresentationAttachmentRecord.create(in: db)
        try PresentationMediaItemRecord.create(in: db)
        try PresentationWaveRecord.create(in: db)
        try db.create(virtualTable: "message_search", using: FTS5()) { t in
            t.column("id").notIndexed()
            t.column("body")
            t.tokenizer = .ascii()
        }
    }
}
